export const PADUKUHAN_LABELS: Record<string, string> = {
  p01: "Banjaran",
  p02: "Slanden",
  p03: "Pantog Kulon",
  p04: "Pantog Wetan",
  p05: "Klangon",
  p06: "Pranan",
  p07: "Potronalan",
  p08: "Beji",
  p09: "Kempong",
  p10: "Tanjung",
  p11: "Duren Sawit",
  p12: "Plengan",
  p13: "Dlingseng",
  p14: "Semawung",
  p15: "Promasan",
  p16: "Semagung",
  p17: "Kajoran",
  p18: "Tonogoro",
  p19: "Puguh",
};
